name: Tests

on:
    push:
        branches: ['**']

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - name: Install pre-commit
              run: pip install pre-commit==2.17.0
            - name: Run pre-commit
              run: SKIP=prettier pre-commit run --all-files

    cdk-mypy:
        runs-on: ubuntu-latest
        needs: lint
        defaults:
          run:
            working-directory: cdk
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - name: Install dependencies
              run: pip install -r requirements.txt -r requirements-dev.txt
            - name: Run mypy
              run: mypy .

    cdk-pytest:
        runs-on: ubuntu-latest
        needs: lint
        defaults:
          run:
            working-directory: cdk
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - name: Install dependencies
              run: pip install -r requirements.txt -r requirements-dev.txt
            - name: Run pytest
              run: pytest tests/

    jest:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            actions: write
        steps:
            - uses: actions/checkout@v3
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Setup Docker Compose
              run: |
                sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            - name: Build Nextjs Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: docker/nextjs/Dockerfile
                push: false
                tags: igvf-ui-nextjs
                cache-from: type=gha,scope=igvf-ui-nextjs
                cache-to: type=gha,scope=igvf-ui-nextjs
            - name: Run tests
              run: docker-compose -f docker-compose.test.yml up --exit-code-from nextjs
